sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
env:
  - PACKAGES="Django>=1.11,<1.12"
  - PACKAGES="Django>=2.0,<2.1"
  - PACKAGES="Django>=2.1,<2.2"
  - PACKAGES="Django>=2.2,<2.3"
matrix:
  exclude:
  - python: '2.7'
    env: PACKAGES="Django>=2.0,<2.1"
  - python: '2.7'
    env: PACKAGES="Django>=2.1,<2.2"
  - python: '2.7'
    env: PACKAGES="Django>=2.2,<2.3"
  allow_failure:
    - env: PACKAGES="Django>=2.1,<2.2"

before_install:
  - pip install codecov
install:
  - travis_retry pip install $PACKAGES -e .

script:
  - coverage run --source=threadedcomments runtests.py

after_success:
- codecov

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#django-fluent"
    template:
      - "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
    skip_join: true
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
